---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_paths:
    - spec/
  fixme:
    enabled: true
  rubocop:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.rake"
exclude_paths:
- bin/
- config/
- public/
- tmp/
- db/
