version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .docker-dev.env
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true

  db:
    image: postgres:11.5-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .docker-dev.env
    ports:
      - "5432"

  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6378:6379"
